### ISSUE TITLE
On_site function stops iteration

### ISSUE THREAD

**Issue by VarunFuego17** [m-rots/violet#16]
When an agent enters a site after collision it will iterate for some frames  checking( if on_site) and after that happens the function doesn't executes even though an agent is inside a site and just executes when the agent leaves because of collision with the border.

**Comment by m-rots** [comment]
Could you perhaps include a code example which I could use to reproduce this issue? The details you provided are a bit too vague for me to try and come up with a reproduction myself 😅

**Comment by VarunFuego17** [comment]
''' Basic template which prints True when an agent is on_site and prints False when no on_site
However if you run the code you will see that it will return False when the agent is moving inside the sprite of the site image
now on_site only returns True when there is border collision between the two sprites until the agent passed the border to the inside of the site.
''' 
from vi import Agent, Simulation
from vi.config import Config

class Bee(Agent):

    def change_position(self):
        self.there_is_no_escape()
        self.pos += self.move
        if self.on_site():
            print("True")
        else:
            print('False')
(
    Simulation(
        Config(
            image_rotation=True,
            movement_speed=1.5,
            radius=40,
            seed=1,
            fps_limit=60,
        )
    )
        .spawn_site("bubble-small.png", 400, 375)
        .batch_spawn_agents(1, Bee, images=["bees.png"])
        .run()
)

**Comment by m-rots** [comment]
Ah right, this is indeed intended behaviour as we want to support sites of various shapes. If you add a site with an opaque image (such as [`site.png`](https://github.com/m-rots/violet/blob/e2b15cb36805f738eb579d25a9f2bbd1e443cb32/examples/images/site.png)), then you'll see that `True` is printed as long as the pixels collide.
